//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.05 at 08:05:16 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://srsanjay.com/employees", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.srsanjay.employees;
